import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const generalSans = localFont({
  src: [
    {
      path: "/fonts/GeneralSans-Regular.otf",
      weight: "400",
    },
    {
      path: "/fonts/GeneralSans-Medium.otf",
      weight: "500",
    },
    {
      path: "/fonts/GeneralSans-Semibold.otf",
      weight: "600",
    },
    {
      path: "/fonts/GeneralSans-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-generalSans", // Define a CSS variable
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${generalSans.variable} ${archivo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
